/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import org.junit.Test;

import java.util.ArrayList;

import static org.junit.Assert.*;

public class LibraryTest {
    @Test
    public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }

    @Test
    public void testMeanMetho() {
        Library classUnderTest = new Library();

        ArrayList<Double> data = new ArrayList<>();
        data.add(3.4);
        data.add(5.5);
        Double ans = classUnderTest.mean(data);

        assertEquals(4.45, ans, 0.0002);

    }
}

